BIBLE_TRAIN_TEST_DEV_SPLIT = {
    
}


SPEAKER_COMMENTS = {
    "Pito Salas": "50-60 years of age, male from Curaçao who has lived in the US for most of his life, speaking mostly English.",
    "Nydia Ecury": "45-70 years of age, female, likely Nydia Ecury, a famous Aruban poet and writer. File is from the Atlas of Pidgin and Creole Language Structures (APiCS) online archive.",
    "KompasKorsou": "30-40 years of age, male from Curaçao. File(s) from the KompasKorsou Facebook page.",
    "male_matthew_main": "Adult male. One of many speakers from the bible.is dramatic reading of the New Testament.",
    "male_mark_main": "Adult male. One of many principle book narrators from the bible.is dramatic reading of the New Testament.",
    "male_luke_main": "Adult male. One of many principle book narrators from the bible.is dramatic reading of the New Testament.",
    "male_john_main": "Adult male. One of many principle book narrators from the bible.is dramatic reading of the New Testament.",
    "male_acts_main": "Adult male. One of many principle book narrators from the bible.is dramatic reading of the New Testament.",
    "male_paul_main": "Adult male. One of many principle book narrators from the bible.is dramatic reading of the New Testament.",
    "female_hebrews_main": "Adult female. One of many principle book narrators from the bible.is dramatic reading of the New Testament.",
    "male_james_main": "Adult male. One of many principle book narrators from the bible.is dramatic reading of the New Testament.",
    "male_peter_main": "Adult male. One of many principle book narrators from the bible.is dramatic reading of the New Testament.",
    "male_jude_main": "Adult male. One of many principle book narrators from the bible.is dramatic reading of the New Testament.",
    "male_john_main": "Adult male. One of many principle book narrators from the bible.is dramatic reading of the New Testament.",
}

RECORDING_ENV_COMMENTS = {
    "Pito Salas": "Recorded in a quiet room on a 2017 Macbook laptop microphone.",
    "Nydia Ecury": "Low-fidelity recording with some white noise.",
    "KompasKorsou": "Likely from a phone-microphone. Background music algorithmically removed.",
    "male_matthew_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
    "male_mark_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
    "male_luke_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
    "male_john_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
    "male_acts_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
    "male_paul_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
    "female_hebrews_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
    "male_james_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
    "male_peter_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
    "male_jude_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
    "male_john_main": "Occasional background noise and effects (crowd commotion, babbling stream, added reverb, etc.) used in the dramatic reading.",
}

LICENSE_BY_SPEAKER = {
    "Pito Salas": "Copyright 2023 Pito Salas",
    "Nydia Ecury": "Creative Commons Attribution 4.0 International",
    "KompasKorsou": "Copyright 2023 KompasKorsou (Facebook)",
    "male_matthew_main": "Copyright",
    "male_mark_main": "Copyright",
    "male_luke_main": "Copyright",
    "male_john_main": "Copyright",
    "male_acts_main": "Copyright",
    "male_paul_main": "Copyright",
    "female_hebrews_main": "Copyright",
    "male_james_main": "Copyright",
    "male_peter_main": "Copyright",
    "male_jude_main": "Copyright",
    "male_john_main": "Copyright",
}

IS_MALE_BY_SPEAKER = {
    "Pito Salas": True,
    "Nydia Ecury": False,
    "KompasKorsou": True,
    "male_matthew_main": True,
    "male_mark_main": True,
    "male_luke_main": True,
    "male_john_main": True,
    "male_acts_main": True,
    "male_paul_main": True,
    "female_hebrews_main": False,
    "male_james_main": True,
    "male_peter_main": True,
    "male_jude_main": True,
    "male_john_main": True,
}

SPEAKER_BY_OTHER_MP3S = {
    "Habai-Nydia_Ecury": "Nydia Ecury",
    "KompasKorsou": "KompasKorsou",
}

BOOKS = {
    1: "Mateo",
    2: "Marko",
    3: "Lukas",
    4: "Huan",
    5: "Echonan",
    6: "Romanonan",
    7: "1 Korintionan",
    8: "2 Korintionan",
    9: "Galatanan",
    10: "Efesionan",
    11: "Filipensenan",
    12: "Kolosensenan",
    13: "1 Tesalonisensenan",
    14: "2 Tesalonisensenan",
    15: "1 Timoteo",
    16: "2 Timoteo",
    17: "Tito",
    18: "Filemon",
    19: "Hebreonan",
    20: "Hakobo",
    21: "1 Pedro",
    22: "2 Pedro",
    23: "1 Huan",
    24: "2 Huan",
    25: "3 Huan",
    26: "Hudas",
    27: "Revelashon",
}

BOOK_NAMES = {v: k for k, v in BOOKS.items()}

# Books are mostly narrated by someone intended to represent the book's author
PRINCIPLE_SPEAKERS_BY_BOOK = {
    "Mateo": "male_matthew_main",
    "Marko": "male_mark_main",
    "Lukas": "male_luke_main",
    "Huan": "male_john_main",
    "Echonan": "male_acts_main",
    "Romanonan": "male_paul_main",
    "1 Korintionan": "male_paul_main",
    "2 Korintionan": "male_paul_main",
    "Galatanan": "male_paul_main",
    "Efesionan": "male_paul_main",
    "Filipensenan": "male_paul_main",
    "Kolosensenan": "male_paul_main",
    "1 Tesalonisensenan": "male_paul_main",
    "2 Tesalonisensenan": "male_paul_main",
    "1 Timoteo": "male_paul_main",
    "2 Timoteo": "male_paul_main",
    "Tito": "male_paul_main",
    "Filemon": "male_paul_main",
    "Hebreonan": "female_hebrews_main",
    "Hakobo": "male_james_main",
    "1 Pedro": "male_peter_main",
    "2 Pedro": "male_peter_main",
    "1 Huan": "male_john_main",
    "2 Huan": "male_john_main",
    "3 Huan": "male_john_main",
    "Hudas": "male_jude_main",
    "Revelashon": "male_john_main",
}


BOOK_SPECIFIC_FILE_NAME_PATTERNS = {
    "Mateo": "B01___{ch:02d}_Matthew_____PA2BSNN1DA.mp3",
    "Marko": "B02___{ch:02d}_Mark________PA2BSNN1DA.mp3",
    "Lukas": "B03___{ch:02d}_Luke________PA2BSNN1DA.mp3",
    "Huan": "B04___{ch:02d}_John________PA2BSNN1DA.mp3",
    "Echonan": "B05___{ch:02d}_Acts________PA2BSNN1DA.mp3",
    "Romanonan": "B06___{ch:02d}_Romans______PA2BSNN1DA.mp3",
    "1 Korintionan": "B07___{ch:02d}_1CorinthiansPA2BSNN1DA.mp3",
    "2 Korintionan": "B08___{ch:02d}_2CorinthiansPA2BSNN1DA.mp3",
    "Galatanan": "B09___{ch:02d}_Galatians___PA2BSNN1DA.mp3",
    "Efesionan": "B10___{ch:02d}_Ephesians___PA2BSNN1DA.mp3",
    "Filipensenan": "B11___{ch:02d}_Philippians_PA2BSNN1DA.mp3",
    "Kolosensenan": "B12___{ch:02d}_Colossians__PA2BSNN1DA.mp3",
    "1 Tesalonisensenan": "B13___{ch:02d}_1Thess______PA2BSNN1DA.mp3",
    "2 Tesalonisensenan": "B14___{ch:02d}_2Thess______PA2BSNN1DA.mp3",
    "1 Timoteo": "B15___{ch:02d}_1Timothy____PA2BSNN1DA.mp3",
    "2 Timoteo": "B16___{ch:02d}_2Timothy____PA2BSNN1DA.mp3",
    "Tito": "B17___{ch:02d}_Titus_______PA2BSNN1DA.mp3",
    "Filemon": "B18___{ch:02d}_Philemon____PA2BSNN1DA.mp3",
    "Hebreonan": "B19___{ch:02d}_Hebrews_____PA2BSNN1DA.mp3",
    "Hakobo": "B20___{ch:02d}_James_______PAPBSNN1DA.mp3",
    "1 Pedro": "B21___{ch:02d}_1Peter______PA2BSNN1DA.mp3",
    "2 Pedro": "B22___{ch:02d}_2Peter______PA2BSNN1DA.mp3",
    "1 Huan": "B23___{ch:02d}_1John_______PA2BSNN1DA.mp3",
    "2 Huan": "B24___{ch:02d}_2John_______PA2BSNN1DA.mp3",
    "3 Huan": "B25___{ch:02d}_3John_______PA2BSNN1DA.mp3",
    "Hudas": "B26___{ch:02d}_Jude________PA2BSNN1DA.mp3",
    "Revelashon": "B27___{ch:02d}_Revelation__PA2BSNN1DA.mp3",
}

SPANISH_NUMBERS = {
    "cero": 0,
    "uno": 1,
    "dos": 2,
    "tres": 3,
    "cuatro": 4,
    "cinco": 5,
    "seis": 6,
    "siete": 7,
    "ocho": 8,
    "nueve": 9,
    "diez": 10,
    "once": 11,
    "doce": 12,
    "trece": 13,
    "catorce": 14,
    "quince": 15,
    "dieciséis": 16,
    "diecisiete": 17,
    "dieciocho": 18,
    "diecinueve": 19,
    "veinte": 20,
    "treinta": 30,
    "cuarenta": 40,
    "cincuenta": 50,
    "sesenta": 60,
    "setenta": 70,
    "ochenta": 80,
    "noventa": 90,
    "cien": 100,
}
